spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 930118Qq
    url: jdbc:mysql://localhost:3306/sso?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sso2
  port: 8082